name: Release

on:
  workflow_call:
    inputs:
      java_runtime:
        description: "Java version to build with"
        required: false
        default: 25
        type: number
      release_snapshot_as_draft:
        description: "Mark GitHub releases as draft when the version is suffixed with \"SNAPSHOT\""
        required: false
        default: true
        type: boolean
      is_gradle_plugin:
        description: "Whether the project is a Gradle plugin"
        required: false
        default: false
        type: boolean
      git_cliff_config_path:
        description: "Path to the git-cliff config file within the repo"
        required: false
        type: string
      tag_name:
        description: "Tag name to tie the GitHub release to"
        required: false
        default: "${{ github.ref_name }}"
        type: string
    secrets:
      HBOYD_GPG_KEY_ID:
        description: "GPG Key ID to sign artifacts with for Hboyd projects"
        required: false
      HBOYD_GPG_KEY:
        description: "GPG Key Armor file to sign artifacts with for Hboyd projects"
        required: false
      HBOYD_GPG_PASSWORD:
        description: "GPG Key Password to sign artifacts with for Hboyd projects"
        required: false
      HBOYD_SONATYPE_USERNAME:
        description: "Hboyd Sonatype username"
        required: false
      HBOYD_SONATYPE_PASSWORD:
        description: "Hboyd Sonatype password"
        required: false
      HBOYD_DEV_USERNAME:
        description: "Hboyd Dev maven repo username"
        required: false
      HBOYD_DEV_PASSWORD:
        description: "Hboyd Dev maven repo password"
        required: false
      GRADLE_PLUGIN_PORTAL_API_KEY:
        description: "Gradle Plugin Portal API key"
        required: false
      GRADLE_PLUGIN_PORTAL_API_SECRET:
        description: "Gradle Plugin Portal API secret"
        required: false


jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Environment"
        uses: "hboyd2003/github-ci/actions/java-env-setup@master"
        with:
          runtime_version: 25

      - name: "Build with Gradle"
        run: ./gradlew build

      - name: "Upload Test Results"
        if: "${{ always() }}" # Run even after build failure
        uses: "actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f" # v7.0.0
        with:
          name: "test-results"
          path: |
            build/reports/
            */build/reports/

      - name: "Grab Version Details & Disable Further Dependency Graph Generation"
        id: "grab_version"
        run: |
          VERSION=$(./gradlew -q printVersionWithoutBuildMetadata)
          echo VERSION= $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          if [ "$(echo $VERSION | grep '\-SNAPSHOT')" ]; then
            RELEASE=false
            CLIFF_ARGS="--unreleased --strip header"
          else
            RELEASE=true
            CLIFF_ARGS="--latest --strip header"
          fi
          
          echo RELEASE=$RELEASE
          echo "RELEASE=$RELEASE" >> $GITHUB_OUTPUT
          
          echo CLIFF_ARGS=$CLIFF_ARGS
          echo "CLIFF_ARGS=$CLIFF_ARGS" >> $GITHUB_OUTPUT
          
          echo "GITHUB_DEPENDENCY_GRAPH_ENABLED=false" >> $GITHUB_ENV
          export GITHUB_DEPENDENCY_GRAPH_ENABLED=false
        shell: bash

      - name: "Determine Gradle Tasks"
        id: "determine_gradle_tasks"
        run: |
          if [[ "${{ inputs.is_gradle_plugin }}" == "true" && "${{ steps.grab_version.outputs.RELEASE }}" == "true" ]]; then
            GRADLE_TASKS="publish publishPlugins"
          else
            GRADLE_TASKS=publish
          fi
          
          echo GRADLE_TASKS=$GRADLE_TASKS
          echo "GRADLE_TASKS=$GRADLE_TASKS" >> $GITHUB_OUTPUT
        shell: bash


      - name: "Publish"
        run: ./gradlew ${{ steps.determine_gradle_tasks.outputs.GRADLE_TASKS }}
        env:
          ORG_GRADLE_PROJECT_hboydSigningKeyId: ${{ secrets.HBOYD_GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_hboydSigningKey: ${{ secrets.HBOYD_GPG_KEY }}
          ORG_GRADLE_PROJECT_hboydSigningPassword: ${{ secrets.HBOYD_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.HBOYD_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.HBOYD_SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_hboydDevUsername: ${{ secrets.HBOYD_DEV_USERNAME }}
          ORG_GRADLE_PROJECT_hboydDevPassword: ${{ secrets.HBOYD_DEV_PASSWORD }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGIN_PORTAL_API_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGIN_PORTAL_API_SECRET }}

      - name: "Generate changelog"
        uses: "hboyd2003/github-ci/actions/generate-change-log@master"
        id: "generate_changelog"
        with:
          git_cliff_config_path: ${{ inputs.git_cliff_config_path }}

      - name: "Create GH Release"
        uses: "softprops/action-gh-release@v2.5.0"
        with:
          body: ${{ steps.generate_changelog.outputs.content  }}
          draft: ${{ (steps.grab_version.outputs.RELEASE == 'false' && !inputs.release_snapshot_as_draft) || steps.grab_version.outputs.RELEASE == 'true' }}
          prerelease: ${{ steps.grab_version.outputs.RELEASE == 'false' }}
          tag_name: ${{ inputs.tag_name }}
          files: |
            build/libs/*
  upload-dependencies:
    name: "Submit Dependency Graph"
    if: always()
    needs: "release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Submit Dependency Graph"
        uses: "gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c" # v5.0.2
        with:
          dependency-graph: "download-and-submit"