name: Tag Snapshot
on:
  workflow_call:


concurrency:
  cancel-in-progress: true
  group: tag-snapshot

jobs:
  tag-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: "Configure Git"
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: "Tag Snapshot"
        run: |
          git tag -d snapshot
          git push origin --delete snapshot
          git tag -a snapshot -m "Snapshot"
          git push origin --tags --force